image: php:8.1

definitions:
  services:
    elasticsearch:
      image: magento/magento-cloud-docker-elasticsearch:7.11-1.3.2
      variables:
        ES_SETTING_DISCOVERY_TYPE: single-node
        ES_JAVA_OPTS: '-Xms512m -Xmx512m'
        
    mariadb:
      image: mariadb:10.4
      variables:
        MYSQL_DATABASE: magento_integration_tests
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: rootpassword
    rabbitmq:
      image: rabbitmq:3.9-management
      memory: 512
      env:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

  steps:
    - step: &test-step
        name: Integration Test
        script:
          - apt-get update && apt-get install -y unzip libpng-dev libicu-dev libxslt-dev libzip-dev zlib1g-dev libjpeg-dev mariadb-client procps
          - docker-php-ext-configure gd --with-jpeg
          - docker-php-ext-install gd bcmath zip intl xsl pdo_mysql soap sockets
          - export COMPOSER_ALLOW_SUPERUSER=1
          - sleep 20 # Wait for elasticsearch
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer create-project --repository-url="https://mirror.mage-os.org/" "magento/project-community-edition:>=2.4.5 <2.4.6" ./magento2 --no-install
          - echo "memory_limit = -1" > $PHP_INI_DIR/conf.d/php-memory-limits.ini

            # for local source
            # composer config repositories.local path $BITBUCKET_CLONE_DIR
          - |
            cd magento2
            composer config --no-interaction allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
            composer config --no-interaction allow-plugins.laminas/laminas-dependency-plugin true
            composer config --no-interaction allow-plugins.magento/* true
            echo composer.json
            composer install
          - |
            cd dev/tests/integration
            sed -i "s/'db-host' => 'localhost'/'db-host' => '127.0.0.1'/" etc/install-config-mysql.php.dist
            sed -i "s/'db-user' => 'root'/'db-user' => 'user'/" etc/install-config-mysql.php.dist
            sed -i "s/'db-password' => '123123q'/'db-password' => 'password'/" etc/install-config-mysql.php.dist
            sed -i "s/'elasticsearch-host' => 'localhost'/'elasticsearch-host' => '127.0.0.1'/" etc/install-config-mysql.php.dist
            sed -i "s/'amqp-host' => 'localhost'/'amqp-host' => '127.0.0.1'/" etc/install-config-mysql.php.dist
            php ../../../vendor/bin/phpunit ../../../vendor/magento/magento2-base/dev/tests/integration/testsuite/Magento/Framework/MessageQueue/TopologyTest.php

        services: 
          - mariadb
          - elasticsearch
          - rabbitmq

pipelines:
  branches:
    production:
      - step: *test-step